#!/bin/bash
PARAMS="$@"
CYGWIN="C:\/cygwin64"

# Regex user path to UNIX style path
PARAMS_LINUX=${PARAMS/$CYGWIN/}

# Find inventory file generated by Vagrant 
INVENTORY=$(echo $PARAMS_LINUX | sed 's/.*inventory-file=\([^  ]*\).*/\1\/vagrant_ansible_inventory/')

# Regex private key file path to UNIX style path
sed -i "s/$CYGWIN//" $INVENTORY

/usr/bin/ansible-playbook $PARAMS_LINUX