- name: Install common tools used by all servers
  yum: name={{ item }} state=installed
  with_items:
    - lsof
    - tree
    - elinks
    - telnet
    - screen
    - bind-utils 
    - net-tools 
    - policycoreutils-python
    - traceroute
    - epel-release

- name: Congfigure /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    insertafter: EOF
    state: present
  with_items:
    - '1.2.3.4     home    home1   home-1'
    - '1.2.3.5     server1     server-1    lfcs-practice.com   server1.lfcs-practice.com'
    - '1.2.3.6     server2     server-2'
